# Fibonacci sequence: generated by adding previous two terms
# For example: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89

# Find the sum of the even valued terms up to 4 million.

# create array with fib sequence up to 4 million
fib = [1, 1]
n = 1
index = 0
while fib[-1] < 4_000_000
  index += 1
  n = n + fib[index - 1]
    fib.push(n)
end

#create even fib array
fibEven = []
fib.each { |n|
  if n % 2 == 0
    fibEven.push(n)
  end
 }

# sum array
sum = fibEven.inject { |sum, x| sum + x }
